Repository viamrobotics/api, pull requests merged in 2023-09, with the labels that each got.

#341 [RSDK-4739] add end status msg to cloudslam and internal data to data
  app/cloudslam/v1/cloud_slam.pb.go
  app/data/v1/data.pb.go
  component/arm/v1/arm.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/app/cloudslam/v1/cloud_slam_pb.d.ts
  gen/js/app/cloudslam/v1/cloud_slam_pb.js
  gen/js/app/data/v1/data_pb.d.ts
  gen/js/app/data/v1/data_pb.js
  proto/viam/app/cloudslam/v1/cloud_slam.proto
  proto/viam/app/data/v1/data.proto
  service/motion/v1/motion.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
Labels: protos-compiled

#350 [DATA-1918] add internal data to delete requests
  app/data/v1/data.pb.go
  component/arm/v1/arm.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/app/data/v1/data_pb.d.ts
  gen/js/app/data/v1/data_pb.js
  proto/viam/app/data/v1/data.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/slam/v1/slam.pb.gw.go
Labels: protos-compiled

#333 APP-2536 - Cleanup unused orgid fields in module protos
  app/v1/app.pb.go
  component/arm/v1/arm.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  proto/viam/app/v1/app.proto
Labels: protos-compiled

#353 APP-2625: getRobotAPIKeys request
  app/v1/app.pb.go
  app/v1/app.pb.gw.go
  app/v1/app_grpc.pb.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  gen/js/app/v1/app_grpc_web_pb.js
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  gen/js/app/v1/app_pb_service.d.ts
  gen/js/app/v1/app_pb_service.js
  proto/viam/app/v1/app.proto
  service/motion/v1/motion.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/slam/v1/slam.pb.gw.go
Labels: protos-compiled

#345 DATA-1889 - Add ConfigureDatabaseUser to the API
  app/data/v1/data.pb.go
  app/data/v1/data.pb.gw.go
  app/data/v1/data_grpc.pb.go
  gen/js/app/data/v1/data_grpc_web_pb.js
  gen/js/app/data/v1/data_pb.d.ts
  gen/js/app/data/v1/data_pb.js
  gen/js/app/data/v1/data_pb_service.d.ts
  gen/js/app/data/v1/data_pb_service.js
  proto/viam/app/data/v1/data.proto
  service/datamanager/v1/data_manager.pb.gw.go
Labels: protos-compiled

#351 RSDK-4199 - Remove pbstruct from mlmodel.proto
  component/audioinput/v1/audioinput.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  gen/js/service/mlmodel/v1/mlmodel_pb.d.ts
  gen/js/service/mlmodel/v1/mlmodel_pb.js
  proto/viam/service/mlmodel/v1/mlmodel.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/mlmodel/v1/mlmodel.pb.go
  service/motion/v1/motion.pb.gw.go
  service/slam/v1/slam.pb.gw.go
Labels: protos-compiled

#349 DATA-1091 - Docs update: Public data API documentation
  app/data/v1/data.pb.go
  app/datasync/v1/data_sync.pb.go
  app/datasync/v1/data_sync_grpc.pb.go
  component/arm/v1/arm.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  proto/viam/app/data/v1/data.proto
  proto/viam/app/datasync/v1/data_sync.proto
  service/sensors/v1/sensors.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled

#356 DATA-1940 - API changes for datasets
  app/data/v1/data.pb.go
  app/data/v1/data.pb.gw.go
  app/data/v1/data_grpc.pb.go
  app/dataset/v1/dataset.pb.go
  app/dataset/v1/dataset.pb.gw.go
  app/dataset/v1/dataset_grpc.pb.go
  component/board/v1/board.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  gen/js/app/data/v1/data_grpc_web_pb.js
  gen/js/app/data/v1/data_pb.d.ts
  gen/js/app/data/v1/data_pb.js
  gen/js/app/data/v1/data_pb_service.d.ts
  gen/js/app/data/v1/data_pb_service.js
  gen/js/app/dataset/v1/dataset_grpc_web_pb.js
  gen/js/app/dataset/v1/dataset_pb.d.ts
  gen/js/app/dataset/v1/dataset_pb.js
  gen/js/app/dataset/v1/dataset_pb_service.d.ts
  gen/js/app/dataset/v1/dataset_pb_service.js
  proto/viam/app/data/v1/data.proto
  proto/viam/app/dataset/v1/dataset.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/slam/v1/slam.pb.gw.go
Labels: enhancement, protos-compiled

#346 APP-2589: Add support for DeleteKey and ListKeys endpoints
  app/data/v1/data.pb.go
  app/v1/app.pb.go
  app/v1/app.pb.gw.go
  app/v1/app_grpc.pb.go
  component/arm/v1/arm.pb.gw.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/app/v1/app_grpc_web_pb.js
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  gen/js/app/v1/app_pb_service.d.ts
  gen/js/app/v1/app_pb_service.js
  proto/viam/app/v1/app.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/slam/v1/slam.pb.gw.go
Labels: protos-compiled

#357 RSDK-4786 add methods to expose motion plans to users
  component/camera/v1/camera.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  gen/js/service/motion/v1/motion_grpc_web_pb.js
  gen/js/service/motion/v1/motion_pb.d.ts
  gen/js/service/motion/v1/motion_pb.js
  gen/js/service/motion/v1/motion_pb_service.d.ts
  gen/js/service/motion/v1/motion_pb_service.js
  proto/viam/service/motion/v1/motion.proto
  service/motion/v1/motion.pb.go
  service/motion/v1/motion.pb.gw.go
  service/motion/v1/motion_grpc.pb.go
  service/shell/v1/shell.pb.gw.go
  service/slam/v1/slam.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: enhancement, protos-compiled

#359 [DATA-1861] Remove DeleteTabularDataByFilter from API
  app/data/v1/data.pb.go
  app/data/v1/data.pb.gw.go
  app/data/v1/data_grpc.pb.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  gen/js/app/data/v1/data_grpc_web_pb.js
  gen/js/app/data/v1/data_pb.d.ts
  gen/js/app/data/v1/data_pb.js
  gen/js/app/data/v1/data_pb_service.d.ts
  gen/js/app/data/v1/data_pb_service.js
  proto/viam/app/data/v1/data.proto
  service/shell/v1/shell.pb.gw.go
  service/slam/v1/slam.pb.gw.go
Labels: protos-compiled

#362 Rotatekey protos
  app/v1/app.pb.go
  app/v1/app.pb.gw.go
  app/v1/app_grpc.pb.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  gen/js/app/v1/app_grpc_web_pb.js
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  gen/js/app/v1/app_pb_service.d.ts
  gen/js/app/v1/app_pb_service.js
  proto/viam/app/v1/app.proto
  service/motion/v1/motion.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled

#365 APP-2335 Add EndUserService definition
  app/data/v1/data.pb.go
  app/data/v1/data.pb.gw.go
  app/data/v1/data_grpc.pb.go
  app/v1/end_user.pb.go
  app/v1/end_user.pb.gw.go
  app/v1/end_user_grpc.pb.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/app/data/v1/data_grpc_web_pb.js
  gen/js/app/data/v1/data_pb.d.ts
  gen/js/app/data/v1/data_pb.js
  gen/js/app/data/v1/data_pb_service.d.ts
  gen/js/app/data/v1/data_pb_service.js
  gen/js/app/v1/end_user_grpc_web_pb.js
  gen/js/app/v1/end_user_pb.d.ts
  gen/js/app/v1/end_user_pb.js
  gen/js/app/v1/end_user_pb_service.d.ts
  gen/js/app/v1/end_user_pb_service.js
  proto/viam/app/v1/end_user.proto
  service/motion/v1/motion.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/slam/v1/slam.pb.gw.go
Labels: enhancement, protos-compiled

#364 RSDK-4786-dry-proposal
  component/arm/v1/arm.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  gen/js/service/motion/v1/motion_pb.d.ts
  gen/js/service/motion/v1/motion_pb.js
  proto/viam/service/motion/v1/motion.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/motion/v1/motion.pb.go
Labels: protos-compiled

#367 Retrigger build
  component/arm/v1/arm.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/service/motion/v1/motion_pb.d.ts
  gen/js/service/motion/v1/motion_pb.js
  proto/viam/service/motion/v1/motion.proto
  service/motion/v1/motion.pb.go
  service/motion/v1/motion_grpc.pb.go
  service/navigation/v1/navigation.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: bug, protos-compiled

#366 add CreateKeyFromExistingKeyAuthorizationsResponse proto methods
  app/v1/app.pb.go
  app/v1/app.pb.gw.go
  app/v1/app_grpc.pb.go
  component/base/v1/base.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  gen/js/app/v1/app_grpc_web_pb.js
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  gen/js/app/v1/app_pb_service.d.ts
  gen/js/app/v1/app_pb_service.js
  proto/viam/app/v1/app.proto
  service/sensors/v1/sensors.pb.gw.go
  service/slam/v1/slam.pb.gw.go
Labels: protos-compiled

#368 RSDK-5181 Add analog write to board API
  component/board/v1/board.pb.go
  component/camera/v1/camera.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  gen/js/component/board/v1/board_pb.d.ts
  gen/js/component/board/v1/board_pb.js
  proto/viam/component/board/v1/board.proto
  service/navigation/v1/navigation.pb.gw.go
  service/shell/v1/shell.pb.gw.go
Labels: protos-compiled

#371 RSDK-5181 RPC analog writer
  component/arm/v1/arm.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/board/v1/board.pb.go
  component/board/v1/board.pb.gw.go
  component/board/v1/board_grpc.pb.go
  component/encoder/v1/encoder.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  gen/js/component/board/v1/board_grpc_web_pb.js
  gen/js/component/board/v1/board_pb_service.d.ts
  gen/js/component/board/v1/board_pb_service.js
  proto/viam/component/board/v1/board.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/motion/v1/motion.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled
