Repository viamrobotics/api, pull requests merged in 2024-10, with the labels that each got.

#559 DATA-3210 - Add MLInference service and GetInference RPC to proto
  app/mlinference/v1/ml_inference.pb.go
  app/mlinference/v1/ml_inference.pb.gw.go
  app/mlinference/v1/ml_inference_grpc.pb.go
  component/base/v1/base.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  gen/js/app/mlinference/v1/ml_inference_grpc_web_pb.js
  gen/js/app/mlinference/v1/ml_inference_pb.d.ts
  gen/js/app/mlinference/v1/ml_inference_pb.js
  gen/js/app/mlinference/v1/ml_inference_pb_service.d.ts
  gen/js/app/mlinference/v1/ml_inference_pb_service.js
  proto/viam/app/mlinference/v1/ml_inference.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/motion/v1/motion.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/shell/v1/shell.pb.gw.go
Labels: protos-compiled, safe to test

#561 APP-6153 add token to StartBuild for private checkout
  app/build/v1/build.pb.go
  component/base/v1/base.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  gen/js/app/build/v1/build_pb.d.ts
  gen/js/app/build/v1/build_pb.js
  proto/viam/app/build/v1/build.proto
  service/motion/v1/motion.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/slam/v1/slam.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled, safe to test

#564 APP-6580: Update billing protos for multiple billing tiers
  app/v1/billing.pb.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/app/v1/billing_pb.d.ts
  gen/js/app/v1/billing_pb.js
  proto/viam/app/v1/billing.proto
  service/motion/v1/motion.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/slam/v1/slam.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: safe to test, ready-for-protos

#565 add `StartBuildRequest.workdir` field
  app/build/v1/build.pb.go
  component/arm/v1/arm.pb.gw.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/app/build/v1/build_pb.d.ts
  gen/js/app/build/v1/build_pb.js
  proto/viam/app/build/v1/build.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/generic/v1/generic.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/slam/v1/slam.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled, safe to test

#562 [RSDK-8921] Add extra field to DiscoveryQuery
  component/generic/v1/generic.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/robot/v1/robot_pb.d.ts
  gen/js/robot/v1/robot_pb.js
  proto/viam/robot/v1/robot.proto
  robot/v1/robot.pb.go
  service/slam/v1/slam.pb.gw.go
Labels: safe to test

#568 DATA-3251 - Change TabularDataByMQL & SQL to return raw BSON
  app/data/v1/data.pb.go
  component/base/v1/base.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  gen/js/app/data/v1/data_pb.d.ts
  gen/js/app/data/v1/data_pb.js
  proto/viam/app/data/v1/data.proto
  service/generic/v1/generic.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled, safe to test

#569 APP-6686 granular constraints for uploads and in config request
  app/v1/app.pb.go
  app/v1/robot.pb.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  gen/js/app/v1/robot_pb.d.ts
  gen/js/app/v1/robot_pb.js
  proto/viam/app/v1/app.proto
  proto/viam/app/v1/robot.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/motion/v1/motion.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/shell/v1/shell.pb.gw.go
Labels: protos-compiled, safe to test

#575 RSDK-9125 add MoveThroughJointPositions proto
  component/arm/v1/arm.pb.go
  component/arm/v1/arm.pb.gw.go
  component/arm/v1/arm_grpc.pb.go
  component/base/v1/base.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  gen/js/component/arm/v1/arm_grpc_web_pb.js
  gen/js/component/arm/v1/arm_pb.d.ts
  gen/js/component/arm/v1/arm_pb.js
  gen/js/component/arm/v1/arm_pb_service.d.ts
  gen/js/component/arm/v1/arm_pb_service.js
  proto/viam/component/arm/v1/arm.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/generic/v1/generic.pb.gw.go
  service/motion/v1/motion.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
Labels: safe to test, ready-for-protos

#577 RSDK-8976 - Add stream server options protos
  component/arm/v1/arm.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/google/api/client_pb.d.ts
  gen/js/google/api/client_pb.js
  gen/js/stream/v1/stream_grpc_web_pb.js
  gen/js/stream/v1/stream_pb.d.ts
  gen/js/stream/v1/stream_pb.js
  gen/js/stream/v1/stream_pb_service.d.ts
  gen/js/stream/v1/stream_pb_service.js
  proto/viam/stream/v1/stream.proto
  service/generic/v1/generic.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/slam/v1/slam.pb.gw.go
  service/vision/v1/vision.pb.gw.go
  stream/v1/stream.pb.go
  stream/v1/stream.pb.gw.go
  stream/v1/stream_grpc.pb.go
Labels: protos-compiled, safe to test

#576 APP-6392: Update fragment protos
  app/v1/app.pb.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  proto/viam/app/v1/app.proto
  service/motion/v1/motion.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled, safe to test
