Repository viamrobotics/api, pull requests merged in 2024-12, with the labels that each got.

#600 DATA-3440 (#2) Update ExportTabularData response message
  app/data/v1/data.pb.go
  gen/js/app/data/v1/data_pb.d.ts
  gen/js/app/data/v1/data_pb.js
  proto/viam/app/data/v1/data.proto
Labels: protos-compiled, safe to test

#601 DATA-3440 (#3) Update ExportTabularData response method_parameters
  app/data/v1/data.pb.go
  gen/js/app/data/v1/data_pb.d.ts
  gen/js/app/data/v1/data_pb.js
  proto/viam/app/data/v1/data.proto
Labels: protos-compiled, safe to test

#596 APP-7101 Add machines in org count to fragments APIs
  app/v1/app.pb.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  gen/js/google/api/client_pb.d.ts
  gen/js/google/api/client_pb.js
  proto/viam/app/v1/app.proto
Labels: protos-compiled, safe to test

#603 RSDK-9439 Add `state` to `GetMachineStatusResponse`
  gen/js/robot/v1/robot_pb.d.ts
  gen/js/robot/v1/robot_pb.js
  proto/viam/robot/v1/robot.proto
  robot/v1/robot.pb.go
Labels: protos-compiled, safe to test

#604 Remove setup script
  Makefile
  README.md
  etc/setup.sh
Labels: protos-compiled

#598 APP-7130: Add Trigger Notification to UsageCostType
  app/v1/billing.pb.go
  gen/js/app/v1/billing_pb.d.ts
  gen/js/app/v1/billing_pb.js
  proto/viam/app/v1/billing.proto
Labels: protos-compiled, safe to test

#605 RSDK-9436 Add `disable_log_deduplication` to robot config
  app/v1/robot.pb.go
  gen/js/app/v1/robot_pb.d.ts
  gen/js/app/v1/robot_pb.js
  proto/viam/app/v1/robot.proto
Labels: protos-compiled, safe to test

#599 APP-2437: update OrgDetails proto for ops dashboard improvements
  app/v1/app.pb.go
  app/v1/app.pb.gw.go
  app/v1/app_grpc.pb.go
  gen/js/app/v1/app_grpc_web_pb.js
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  gen/js/app/v1/app_pb_service.d.ts
  gen/js/app/v1/app_pb_service.js
  proto/viam/app/v1/app.proto
Labels: protos-compiled, safe to test

#602 APP-7159: Add markdown_documentation field for inline module docs
  app/v1/app.pb.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  proto/viam/app/v1/app.proto
Labels: bug, safe to test

#607 APP-7232 Fix fragment usage protos
  app/v1/app.pb.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  proto/viam/app/v1/app.proto
Labels: protos-compiled, safe to test

#608 Data-3460: Adding GetInferenceResponse
  app/mlinference/v1/ml_inference.pb.go
  gen/js/app/mlinference/v1/ml_inference_grpc_web_pb.js
  gen/js/app/mlinference/v1/ml_inference_pb.d.ts
  gen/js/app/mlinference/v1/ml_inference_pb.js
  gen/js/google/rpc/error_details_pb.d.ts
  gen/js/google/rpc/error_details_pb.js
  proto/viam/app/mlinference/v1/ml_inference.proto
Labels: protos-compiled, safe to test

#609 APP-7296: Add description to Module Models
  app/v1/app.pb.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  proto/viam/app/v1/app.proto
Labels: protos-compiled, safe to test, ready-for-protos
