Repository viamrobotics/api, pull requests merged in 2024-11, with the labels that each got.

#579 APP-6794: Add APIs for white-labelled invoicing
  app/v1/app.pb.go
  app/v1/app.pb.gw.go
  app/v1/app_grpc.pb.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  gen/js/app/v1/app_grpc_web_pb.js
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  gen/js/app/v1/app_pb_service.d.ts
  gen/js/app/v1/app_pb_service.js
  proto/viam/app/v1/app.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/slam/v1/slam.pb.gw.go
Labels: safe to test, ready-for-protos

#582 APP-6290 Update list machine fragments proto to return resolved fragments
  app/v1/app.pb.go
  component/arm/v1/arm.pb.gw.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  proto/viam/app/v1/app.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/motion/v1/motion.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/slam/v1/slam.pb.gw.go
Labels: protos-compiled, safe to test

#570 RSDK-8767 - Add remote path and local name to resourceName proto
  common/v1/common.pb.go
  component/arm/v1/arm.pb.gw.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/common/v1/common_pb.d.ts
  gen/js/common/v1/common_pb.js
  proto/viam/common/v1/common.proto
  service/generic/v1/generic.pb.gw.go
  service/motion/v1/motion.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
Labels: protos-compiled, safe to test

#580 Add username to ProcessConfig proto
  app/v1/robot.pb.go
  component/board/v1/board.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/app/v1/robot_pb.d.ts
  gen/js/app/v1/robot_pb.js
  proto/viam/app/v1/robot.proto
  service/motion/v1/motion.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/slam/v1/slam.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled, safe to test

#586 don't fail in compile_protos.yml when diff is empty
  .github/workflows/compile_protos.yml
Labels: safe to test

#587 dependabot updates
  go.mod
  go.sum
Labels: protos-compiled, safe to test

#583 APP-6158: Remove billing support email in favor of shared support email between billing and auth
  app/v1/app.pb.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  proto/viam/app/v1/app.proto
Labels: protos-compiled, safe to test, ready-for-protos

#571 [DATA-3338] add-to-sensor-metadata
  app/data/v1/data.pb.go
  app/datasync/v1/data_sync.pb.go
  gen/js/app/data/v1/data_pb.d.ts
  gen/js/app/data/v1/data_pb.js
  gen/js/app/datasync/v1/data_sync_grpc_web_pb.js
  gen/js/app/datasync/v1/data_sync_pb.d.ts
  gen/js/app/datasync/v1/data_sync_pb.js
  proto/viam/app/data/v1/data.proto
  proto/viam/app/datasync/v1/data_sync.proto
Labels: protos-compiled, safe to test

#589 DATA-3311 - Remove data field from TabularDataByMQL / SQL responses
  app/data/v1/data.pb.go
  gen/js/app/data/v1/data_pb.d.ts
  gen/js/app/data/v1/data_pb.js
  proto/viam/app/data/v1/data.proto
Labels: protos-compiled, safe to test

#581 RSDK-8765 - add cloud meta data to resource status
  gen/js/robot/v1/robot_pb.d.ts
  gen/js/robot/v1/robot_pb.js
  proto/viam/robot/v1/robot.proto
  robot/v1/robot.pb.go
Labels: protos-compiled, safe to test

#593 Add GetLatestTabularData endpoint
  app/data/v1/data.pb.go
  app/data/v1/data.pb.gw.go
  app/data/v1/data_grpc.pb.go
  gen/js/app/data/v1/data_grpc_web_pb.js
  gen/js/app/data/v1/data_pb.d.ts
  gen/js/app/data/v1/data_pb.js
  gen/js/app/data/v1/data_pb_service.d.ts
  gen/js/app/data/v1/data_pb_service.js
  gen/js/google/longrunning/operations_grpc_web_pb.js
  gen/js/google/longrunning/operations_pb.d.ts
  gen/js/google/longrunning/operations_pb.js
  proto/viam/app/data/v1/data.proto
Labels: protos-compiled, safe to test

#592 [APP-6858]: Add all RPC API definitions to AppService that will be required as part of the Self-Service FusionAuth epic.
  app/v1/app.pb.go
  app/v1/app.pb.gw.go
  app/v1/app_grpc.pb.go
  gen/js/app/v1/app_grpc_web_pb.js
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  gen/js/app/v1/app_pb_service.d.ts
  gen/js/app/v1/app_pb_service.js
  proto/viam/app/v1/app.proto
Labels: safe to test, ready-for-protos

#594 DATA-3438 Add resourceSubtype to data source specification
  app/data/v1/data.pb.go
  gen/js/app/data/v1/data_pb.d.ts
  gen/js/app/data/v1/data_pb.js
  proto/viam/app/data/v1/data.proto
Labels: safe to test, ready-for-protos

#595 DATA-3440 Add ExportTabularData + deprecate TabularDataByFilter
  app/data/v1/data.pb.go
  app/data/v1/data.pb.gw.go
  app/data/v1/data_grpc.pb.go
  gen/js/app/data/v1/data_grpc_web_pb.js
  gen/js/app/data/v1/data_pb.d.ts
  gen/js/app/data/v1/data_pb.js
  gen/js/app/data/v1/data_pb_service.d.ts
  gen/js/app/data/v1/data_pb_service.js
  proto/viam/app/data/v1/data.proto
Labels: protos-compiled, safe to test
