Repository viamrobotics/api, pull requests merged in 2024-04, with the labels that each got.

#469 DATA-2438 - Proto changes for ML TrainingJobMetadata
  app/mltraining/v1/ml_training.pb.go
  component/arm/v1/arm.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/app/mltraining/v1/ml_training_pb.d.ts
  gen/js/app/mltraining/v1/ml_training_pb.js
  proto/viam/app/mltraining/v1/ml_training.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/generic/v1/generic.pb.gw.go
  service/motion/v1/motion.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled

#467 RSDK-6829 - Add machine part id to ResourceName message
  common/v1/common.pb.go
  component/encoder/v1/encoder.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  gen/js/common/v1/common_pb.d.ts
  gen/js/common/v1/common_pb.js
  proto/viam/common/v1/common.proto
  service/slam/v1/slam.pb.gw.go
Labels: protos-compiled

#472 Add java sdk to workflow
  .github/workflows/tag_and_release_protos.yml
  component/arm/v1/arm.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  service/datamanager/v1/data_manager.pb.gw.go
  service/slam/v1/slam.pb.gw.go
Labels: protos-compiled

#460 APP-2985: Protos for endpoint to register fusionauth applications
  app/v1/end_user.pb.go
  app/v1/end_user.pb.gw.go
  app/v1/end_user_grpc.pb.go
  component/board/v1/board.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  gen/js/app/v1/end_user_grpc_web_pb.js
  gen/js/app/v1/end_user_pb.d.ts
  gen/js/app/v1/end_user_pb.js
  gen/js/app/v1/end_user_pb_service.d.ts
  gen/js/app/v1/end_user_pb_service.js
  proto/viam/app/v1/end_user.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/slam/v1/slam.pb.gw.go
Labels: protos-compiled

#473 APP-2985: Add update app endpoint and more params to create application request/response
  app/v1/end_user.pb.go
  app/v1/end_user.pb.gw.go
  app/v1/end_user_grpc.pb.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  gen/js/app/v1/end_user_grpc_web_pb.js
  gen/js/app/v1/end_user_pb.d.ts
  gen/js/app/v1/end_user_pb.js
  gen/js/app/v1/end_user_pb_service.d.ts
  gen/js/app/v1/end_user_pb_service.js
  proto/viam/app/v1/end_user.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/motion/v1/motion.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/slam/v1/slam.pb.gw.go
Labels: protos-compiled

#470 DATA-2440 - Add the new PackageType MLTraining and registry types, ModelFramework and ModelType API
  app/mltraining/v1/ml_training.pb.go
  app/packages/v1/packages.pb.go
  app/v1/app.pb.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  gen/js/app/mltraining/v1/ml_training_pb.d.ts
  gen/js/app/mltraining/v1/ml_training_pb.js
  gen/js/app/packages/v1/packages_pb.d.ts
  gen/js/app/packages/v1/packages_pb.js
  gen/js/app/v1/app_grpc_web_pb.js
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  proto/viam/app/mltraining/v1/ml_training.proto
  proto/viam/app/packages/v1/packages.proto
  proto/viam/app/v1/app.proto
  service/motion/v1/motion.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/shell/v1/shell.pb.gw.go
Labels: protos-compiled

#481 APP-3884 new workflow for PRs
  .github/workflows/check_merge_reqs.yml
  .github/workflows/compile_protos.yml
  .github/workflows/license_finder.yml
  .github/workflows/on_pr_approved.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/pullrequest.yml
  README.md
  component/base/v1/base.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  gen/js/app/agent/v1/agent_grpc_web_pb.js
  gen/js/app/build/v1/build_grpc_web_pb.js
  gen/js/app/cloudslam/v1/cloud_slam_grpc_web_pb.js
  gen/js/app/data/v1/data_grpc_web_pb.js
  gen/js/app/dataset/v1/dataset_grpc_web_pb.js
  gen/js/app/datasync/v1/data_sync_grpc_web_pb.js
  gen/js/app/mltraining/v1/ml_training_grpc_web_pb.js
  gen/js/app/packages/v1/packages_grpc_web_pb.js
  gen/js/app/v1/app_grpc_web_pb.js
  gen/js/app/v1/billing_grpc_web_pb.js
  gen/js/app/v1/end_user_grpc_web_pb.js
  gen/js/app/v1/robot_grpc_web_pb.js
  gen/js/component/arm/v1/arm_grpc_web_pb.js
  gen/js/component/audioinput/v1/audioinput_grpc_web_pb.js
  gen/js/component/base/v1/base_grpc_web_pb.js
  gen/js/component/board/v1/board_grpc_web_pb.js
  gen/js/component/camera/v1/camera_grpc_web_pb.js
  gen/js/component/encoder/v1/encoder_grpc_web_pb.js
  gen/js/component/gantry/v1/gantry_grpc_web_pb.js
  gen/js/component/generic/v1/generic_grpc_web_pb.js
  gen/js/component/gripper/v1/gripper_grpc_web_pb.js
  gen/js/component/inputcontroller/v1/input_controller_grpc_web_pb.js
  gen/js/component/motor/v1/motor_grpc_web_pb.js
  gen/js/component/movementsensor/v1/movementsensor_grpc_web_pb.js
  gen/js/component/posetracker/v1/pose_tracker_grpc_web_pb.js
  gen/js/component/powersensor/v1/powersensor_grpc_web_pb.js
  gen/js/component/sensor/v1/sensor_grpc_web_pb.js
  gen/js/component/servo/v1/servo_grpc_web_pb.js
  gen/js/component/testecho/v1/testecho_grpc_web_pb.js
  gen/js/google/bytestream/bytestream_grpc_web_pb.js
  gen/js/google/longrunning/operations_grpc_web_pb.js
  gen/js/module/v1/module_grpc_web_pb.js
  gen/js/provisioning/v1/provisioning_grpc_web_pb.js
  gen/js/robot/v1/robot_grpc_web_pb.js
  gen/js/service/datamanager/v1/data_manager_grpc_web_pb.js
  gen/js/service/generic/v1/generic_grpc_web_pb.js
  gen/js/service/mlmodel/v1/mlmodel_grpc_web_pb.js
  gen/js/service/motion/v1/motion_grpc_web_pb.js
  gen/js/service/navigation/v1/navigation_grpc_web_pb.js
  gen/js/service/sensors/v1/sensors_grpc_web_pb.js
  gen/js/service/shell/v1/shell_grpc_web_pb.js
  gen/js/service/slam/v1/slam_grpc_web_pb.js
  gen/js/service/vision/v1/vision_grpc_web_pb.js
  gen/js/stream/v1/stream_grpc_web_pb.js
  service/generic/v1/generic.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled, safe to test, ready-for-protos

#478 RSDK-6713 RobotService.RestartModule call
  component/arm/v1/arm.pb.gw.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/robot/v1/robot_grpc_web_pb.js
  gen/js/robot/v1/robot_pb.d.ts
  gen/js/robot/v1/robot_pb.js
  gen/js/robot/v1/robot_pb_service.d.ts
  gen/js/robot/v1/robot_pb_service.js
  proto/viam/robot/v1/robot.proto
  robot/v1/robot.pb.go
  robot/v1/robot.pb.gw.go
  robot/v1/robot_grpc.pb.go
  service/datamanager/v1/data_manager.pb.gw.go
  service/motion/v1/motion.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled, safe to test

#484 check out fork in compile_protos
  .github/workflows/compile_protos.yml
Labels: safe to test

#485 fix checkout action in pull_request_target
  .github/workflows/pullrequest.yml
Labels: safe to test

#482 Revert machine part id
  common/v1/common.pb.go
  component/camera/v1/camera.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/common/v1/common_pb.d.ts
  gen/js/common/v1/common_pb.js
  proto/viam/common/v1/common.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/generic/v1/generic.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/slam/v1/slam.pb.gw.go
Labels: protos-compiled, safe to test

#487 RSDK-7181 deprecate robot_part_id in favor of machine_part_id
  component/arm/v1/arm.pb.gw.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  proto/viam/robot/v1/robot.proto
  robot/v1/robot.pb.go
  service/datamanager/v1/data_manager.pb.gw.go
  service/motion/v1/motion.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/slam/v1/slam.pb.gw.go
Labels: safe to test, ready-for-protos

#479 RSDK-7258: change status to message type in board api
  common/v1/common.pb.go
  component/board/v1/board.pb.go
  component/board/v1/board.pb.gw.go
  component/board/v1/board_grpc.pb.go
  component/camera/v1/camera.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  gen/js/common/v1/common_pb.d.ts
  gen/js/common/v1/common_pb.js
  gen/js/component/board/v1/board_grpc_web_pb.js
  gen/js/component/board/v1/board_pb.d.ts
  gen/js/component/board/v1/board_pb.js
  gen/js/component/board/v1/board_pb_service.d.ts
  gen/js/component/board/v1/board_pb_service.js
  proto/viam/common/v1/common.proto
  proto/viam/component/board/v1/board.proto
  service/sensors/v1/sensors.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/slam/v1/slam.pb.gw.go
Labels: safe to test

#486 APP-4415: Add machine cost protos to billing endpoint
  app/v1/billing.pb.go
  component/arm/v1/arm.pb.gw.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  gen/js/app/v1/billing_pb.d.ts
  gen/js/app/v1/billing_pb.js
  proto/viam/app/v1/billing.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/generic/v1/generic.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled, safe to test

#491 shell service: add bidi file copy support
  component/arm/v1/arm.pb.gw.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  gen/js/service/shell/v1/shell_grpc_web_pb.js
  gen/js/service/shell/v1/shell_pb.d.ts
  gen/js/service/shell/v1/shell_pb.js
  gen/js/service/shell/v1/shell_pb_service.d.ts
  gen/js/service/shell/v1/shell_pb_service.js
  proto/viam/service/shell/v1/shell.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/generic/v1/generic.pb.gw.go
  service/shell/v1/shell.pb.go
  service/shell/v1/shell.pb.gw.go
  service/shell/v1/shell_grpc.pb.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled, safe to test

#490 RSDK-7371: remove AnalogStatus and DigitalInterruptStatus from common API
  common/v1/common.pb.go
  component/arm/v1/arm.pb.gw.go
  component/board/v1/board.pb.go
  component/board/v1/board.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  gen/js/common/v1/common_pb.d.ts
  gen/js/common/v1/common_pb.js
  gen/js/component/board/v1/board_pb.d.ts
  gen/js/component/board/v1/board_pb.js
  proto/viam/common/v1/common.proto
  proto/viam/component/board/v1/board.proto
  service/generic/v1/generic.pb.gw.go
  service/motion/v1/motion.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/slam/v1/slam.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: safe to test, ready-for-protos

#476 [APP-4334] Remove unused AgentAppService
  app/agent/v1/agent.pb.go
  app/agent/v1/agent.pb.gw.go
  app/agent/v1/agent_grpc.pb.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  gen/js/app/agent/v1/agent_grpc_web_pb.js
  gen/js/app/agent/v1/agent_pb.d.ts
  gen/js/app/agent/v1/agent_pb.js
  gen/js/app/agent/v1/agent_pb_service.d.ts
  gen/js/app/agent/v1/agent_pb_service.js
  proto/viam/app/agent/v1/agent.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/generic/v1/generic.pb.gw.go
  service/motion/v1/motion.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled, safe to test
