Repository viamrobotics/api, pull requests merged in 2024-05, with the labels that each got.

#492 RSDK-7148: api changes for analogReader
  component/audioinput/v1/audioinput.pb.gw.go
  component/board/v1/board.pb.go
  component/generic/v1/generic.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  gen/js/component/board/v1/board_pb.d.ts
  gen/js/component/board/v1/board_pb.js
  proto/viam/component/board/v1/board.proto
  service/datamanager/v1/data_manager.pb.gw.go
Labels: safe to test

#493 RSDK-7531 - Add GetProperties to vision service
  component/board/v1/board.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  gen/js/service/vision/v1/vision_grpc_web_pb.js
  gen/js/service/vision/v1/vision_pb.d.ts
  gen/js/service/vision/v1/vision_pb.js
  gen/js/service/vision/v1/vision_pb_service.d.ts
  gen/js/service/vision/v1/vision_pb_service.js
  proto/viam/service/vision/v1/vision.proto
  service/vision/v1/vision.pb.go
  service/vision/v1/vision.pb.gw.go
  service/vision/v1/vision_grpc.pb.go
Labels: protos-compiled, safe to test

#494 RSDK-7468: add captureAll method
  component/arm/v1/arm.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  gen/js/service/vision/v1/vision_grpc_web_pb.js
  gen/js/service/vision/v1/vision_pb.d.ts
  gen/js/service/vision/v1/vision_pb.js
  gen/js/service/vision/v1/vision_pb_service.d.ts
  gen/js/service/vision/v1/vision_pb_service.js
  proto/viam/service/vision/v1/vision.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/generic/v1/generic.pb.gw.go
  service/slam/v1/slam.pb.gw.go
  service/vision/v1/vision.pb.go
  service/vision/v1/vision.pb.gw.go
  service/vision/v1/vision_grpc.pb.go
Labels: safe to test, ready-for-protos

#497 [RSDK-7561] Add enable_web_profile to RobotConfig
  app/v1/robot.pb.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  gen/js/app/v1/robot_pb.d.ts
  gen/js/app/v1/robot_pb.js
  proto/viam/app/v1/robot.proto
  service/navigation/v1/navigation.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/slam/v1/slam.pb.gw.go
Labels: protos-compiled, safe to test

#495 Add bounding regions to the API
  common/v1/common.pb.go
  component/base/v1/base.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/common/v1/common_pb.d.ts
  gen/js/common/v1/common_pb.js
  gen/js/service/motion/v1/motion_pb.d.ts
  gen/js/service/motion/v1/motion_pb.js
  gen/js/service/navigation/v1/navigation_pb.d.ts
  gen/js/service/navigation/v1/navigation_pb.js
  proto/viam/common/v1/common.proto
  proto/viam/service/motion/v1/motion.proto
  proto/viam/service/navigation/v1/navigation.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/motion/v1/motion.pb.go
  service/motion/v1/motion.pb.gw.go
  service/navigation/v1/navigation.pb.go
  service/shell/v1/shell.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: safe to test, ready-for-protos

#500 is_directory
  app/packages/v1/packages.pb.go
  component/arm/v1/arm.pb.gw.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  gen/js/app/packages/v1/packages_pb.d.ts
  gen/js/app/packages/v1/packages_pb.js
  proto/viam/app/packages/v1/packages.proto
  service/generic/v1/generic.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/slam/v1/slam.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled, safe to test

#501 Add version to custom training job request
  app/mltraining/v1/ml_training.pb.go
  component/arm/v1/arm.pb.gw.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/app/mltraining/v1/ml_training_pb.d.ts
  gen/js/app/mltraining/v1/ml_training_pb.js
  proto/viam/app/mltraining/v1/ml_training.proto
  service/generic/v1/generic.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled, safe to test

#504 Add tag to the emitted JSON blob
  .github/workflows/tag_and_release_protos.yml
Labels: safe to test

#507 Fix tag_and_release_protos workflow
  .github/workflows/tag_and_release_protos.yml
  component/arm/v1/arm.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  service/datamanager/v1/data_manager.pb.gw.go
  service/motion/v1/motion.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/slam/v1/slam.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled, safe to test

#489 [APP-3685] feat: add rpc to rename API keys
  app/v1/app.pb.go
  app/v1/app.pb.gw.go
  app/v1/app_grpc.pb.go
  component/arm/v1/arm.pb.gw.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  gen/js/app/v1/app_grpc_web_pb.js
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  gen/js/app/v1/app_pb_service.d.ts
  gen/js/app/v1/app_pb_service.js
  proto/viam/app/v1/app.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/motion/v1/motion.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled, safe to test, ready-for-protos

#506 APP-4896: Implement GetAuthApplication API
  app/v1/end_user.pb.go
  app/v1/end_user.pb.gw.go
  app/v1/end_user_grpc.pb.go
  component/camera/v1/camera.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  gen/js/app/v1/end_user_grpc_web_pb.js
  gen/js/app/v1/end_user_pb.d.ts
  gen/js/app/v1/end_user_pb.js
  gen/js/app/v1/end_user_pb_service.d.ts
  gen/js/app/v1/end_user_pb_service.js
  proto/viam/app/v1/end_user.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/motion/v1/motion.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled, safe to test

#510 Undeprecate public fragment field
  app/v1/app.pb.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  proto/viam/app/v1/app.proto
  service/motion/v1/motion.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
Labels: protos-compiled, safe to test

#509 RSDK-7745: Add SetRPM to API
  component/arm/v1/arm.pb.gw.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/motor/v1/motor.pb.go
  component/motor/v1/motor.pb.gw.go
  component/motor/v1/motor_grpc.pb.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/component/motor/v1/motor_grpc_web_pb.js
  gen/js/component/motor/v1/motor_pb.d.ts
  gen/js/component/motor/v1/motor_pb.js
  gen/js/component/motor/v1/motor_pb_service.d.ts
  gen/js/component/motor/v1/motor_pb_service.js
  proto/viam/component/motor/v1/motor.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/motion/v1/motion.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/slam/v1/slam.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled, safe to test

#512 Remove optional from enable_web_profile
  app/v1/robot.pb.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  gen/js/app/v1/robot_pb.d.ts
  gen/js/app/v1/robot_pb.js
  proto/viam/app/v1/robot.proto
  service/generic/v1/generic.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/shell/v1/shell.pb.gw.go
Labels: protos-compiled, safe to test
