Repository viamrobotics/api, pull requests merged in 2024-01, with the labels that each got.

#385 APP-1865: remove all the old billing protos that are not supported
  app/v1/billing.pb.go
  app/v1/billing.pb.gw.go
  app/v1/billing_grpc.pb.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/app/v1/billing_grpc_web_pb.js
  gen/js/app/v1/billing_pb.d.ts
  gen/js/app/v1/billing_pb.js
  gen/js/app/v1/billing_pb_service.d.ts
  gen/js/app/v1/billing_pb_service.js
  proto/viam/app/v1/billing.proto
  service/shell/v1/shell.pb.gw.go
  service/slam/v1/slam.pb.gw.go
Labels: protos-compiled

#426 Rsdk-6117: last PR didn't compile.
  component/arm/v1/arm.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  service/motion/v1/motion.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
Labels: protos-compiled

#425 APP-3557: Add Registry Item External Usage, Updated, Created fields
  app/v1/app.pb.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  gen/js/component/movementsensor/v1/movementsensor_pb.d.ts
  gen/js/component/movementsensor/v1/movementsensor_pb.js
  proto/viam/app/v1/app.proto
  service/shell/v1/shell.pb.gw.go
  service/slam/v1/slam.pb.gw.go
Labels: protos-compiled

#414 RSDK-6185 Add `ModuleLog` method to `RobotService`
  component/arm/v1/arm.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  gen/js/robot/v1/robot_grpc_web_pb.js
  gen/js/robot/v1/robot_pb.d.ts
  gen/js/robot/v1/robot_pb.js
  gen/js/robot/v1/robot_pb_service.d.ts
  gen/js/robot/v1/robot_pb_service.js
  proto/viam/robot/v1/robot.proto
  robot/v1/robot.pb.go
  robot/v1/robot.pb.gw.go
  robot/v1/robot_grpc.pb.go
  service/datamanager/v1/data_manager.pb.gw.go
  service/motion/v1/motion.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
Labels: protos-compiled

#424 RSDK-6058 Deprecate sensors service api
  component/arm/v1/arm.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  proto/viam/service/sensors/v1/sensors.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/motion/v1/motion.pb.gw.go
  service/sensors/v1/sensors.pb.go
  service/sensors/v1/sensors_grpc.pb.go
  service/slam/v1/slam.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled

#421 RSDK-6031 Remove GetLatestMapInfo from SLAM
  component/arm/v1/arm.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/service/slam/v1/slam_grpc_web_pb.js
  gen/js/service/slam/v1/slam_pb.d.ts
  gen/js/service/slam/v1/slam_pb.js
  gen/js/service/slam/v1/slam_pb_service.d.ts
  gen/js/service/slam/v1/slam_pb_service.js
  proto/viam/service/navigation/v1/navigation.proto
  proto/viam/service/slam/v1/slam.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/motion/v1/motion.pb.gw.go
  service/navigation/v1/navigation.pb.go
  service/navigation/v1/navigation.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/slam/v1/slam.pb.go
  service/slam/v1/slam.pb.gw.go
  service/slam/v1/slam_grpc.pb.go
Labels: protos-compiled

#431 Revert "RSDK-6185 Add `ModuleLog` method to `RobotService` (#414)"
  component/arm/v1/arm.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/robot/v1/robot_grpc_web_pb.js
  gen/js/robot/v1/robot_pb.d.ts
  gen/js/robot/v1/robot_pb.js
  gen/js/robot/v1/robot_pb_service.d.ts
  gen/js/robot/v1/robot_pb_service.js
  proto/viam/robot/v1/robot.proto
  robot/v1/robot.pb.go
  robot/v1/robot.pb.gw.go
  robot/v1/robot_grpc.pb.go
  service/datamanager/v1/data_manager.pb.gw.go
  service/generic/v1/generic.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled

#432 [APP-3492] Update agent proto to support arbitrary subsystem config sections
  app/agent/v1/agent.pb.go
  component/arm/v1/arm.pb.gw.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/app/agent/v1/agent_grpc_web_pb.js
  gen/js/app/agent/v1/agent_pb.d.ts
  gen/js/app/agent/v1/agent_pb.js
  proto/viam/app/agent/v1/agent.proto
  service/generic/v1/generic.pb.gw.go
  service/motion/v1/motion.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: enhancement, protos-compiled

#439 RSDK-5471 - [BREAKING] Change RDK implementation of MoveOnMap to MoveOnMapNew
  component/audioinput/v1/audioinput.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/service/motion/v1/motion_pb.d.ts
  gen/js/service/motion/v1/motion_pb.js
  proto/viam/service/motion/v1/motion.proto
  service/motion/v1/motion.pb.go
  service/motion/v1/motion.pb.gw.go
  service/motion/v1/motion_grpc.pb.go
  service/navigation/v1/navigation.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/slam/v1/slam.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: question, protos-compiled

#440 RSDK-6404 - API changes to MoveOnMap
  component/board/v1/board.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/service/motion/v1/motion_pb.d.ts
  gen/js/service/motion/v1/motion_pb.js
  proto/viam/service/motion/v1/motion.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/motion/v1/motion.pb.go
  service/motion/v1/motion.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/slam/v1/slam.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled
