Repository viamrobotics/api, pull requests merged in 2024-07, with the labels that each got.

#521 DATA-2461 - Remove request from TrainingJobMetadata
  app/mltraining/v1/ml_training.pb.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/app/mltraining/v1/ml_training_pb.d.ts
  gen/js/app/mltraining/v1/ml_training_pb.js
  proto/viam/app/mltraining/v1/ml_training.proto
  service/generic/v1/generic.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled, safe to test

#523 [DATA-2390] Document that DeleteTabularData uses UTC
  proto/viam/app/data/v1/data.proto
Labels: safe to test

#526 RSDK-8083: add LogPatternConfig field to RobotConfig API
  app/data/v1/data.pb.go
  app/v1/robot.pb.go
  component/arm/v1/arm.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  gen/js/app/v1/robot_pb.d.ts
  gen/js/app/v1/robot_pb.js
  proto/viam/app/v1/robot.proto
  service/generic/v1/generic.pb.gw.go
  service/motion/v1/motion.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled, safe to test

#527 RSDK-7899 Add MachineStatus to RobotService
  component/audioinput/v1/audioinput.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  gen/js/robot/v1/robot_grpc_web_pb.js
  gen/js/robot/v1/robot_pb.d.ts
  gen/js/robot/v1/robot_pb.js
  gen/js/robot/v1/robot_pb_service.d.ts
  gen/js/robot/v1/robot_pb_service.js
  proto/viam/robot/v1/robot.proto
  robot/v1/robot.pb.go
  robot/v1/robot.pb.gw.go
  robot/v1/robot_grpc.pb.go
  service/generic/v1/generic.pb.gw.go
  service/motion/v1/motion.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
Labels: safe to test, ready-for-protos

#524 [APP-5400]: Add GetFragmentHistory proto
  app/v1/app.pb.go
  app/v1/app.pb.gw.go
  app/v1/app_grpc.pb.go
  component/arm/v1/arm.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/app/v1/app_grpc_web_pb.js
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  gen/js/app/v1/app_pb_service.d.ts
  gen/js/app/v1/app_pb_service.js
  proto/viam/app/v1/app.proto
  service/generic/v1/generic.pb.gw.go
  service/motion/v1/motion.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled, safe to test

#525 [APP-5420] Add ListMachineFragments request and response
  app/v1/app.pb.go
  app/v1/app.pb.gw.go
  app/v1/app_grpc.pb.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/sensor/v1/sensor.pb.gw.go
  gen/js/app/v1/app_grpc_web_pb.js
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  gen/js/app/v1/app_pb_service.d.ts
  gen/js/app/v1/app_pb_service.js
  proto/viam/app/v1/app.proto
  service/sensors/v1/sensors.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled, safe to test

#530 Add revision field to config
  app/v1/robot.pb.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/app/v1/robot_pb.d.ts
  gen/js/app/v1/robot_pb.js
  proto/viam/app/v1/robot.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/shell/v1/shell.pb.gw.go
Labels: safe to test, ready-for-protos

#531 RSDK-8228 Add config status to machine status API
  component/audioinput/v1/audioinput.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/robot/v1/robot_pb.d.ts
  gen/js/robot/v1/robot_pb.js
  proto/viam/robot/v1/robot.proto
  robot/v1/robot.pb.go
  service/datamanager/v1/data_manager.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/slam/v1/slam.pb.gw.go
Labels: safe to test, ready-for-protos

#532 DATA-2792 - Add URL to UpdateRegistryItemRequest, but make it optional
  app/v1/app.pb.go
  component/base/v1/base.pb.gw.go
  component/board/v1/board.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  gen/js/google/api/field_info_pb.d.ts
  gen/js/google/api/field_info_pb.js
  proto/viam/app/v1/app.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled, safe to test

#534 Data 2816/get training job logs
  app/mltraining/v1/ml_training.pb.go
  app/mltraining/v1/ml_training.pb.gw.go
  app/mltraining/v1/ml_training_grpc.pb.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/movementsensor/v1/movementsensor.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/app/mltraining/v1/ml_training_grpc_web_pb.js
  gen/js/app/mltraining/v1/ml_training_pb.d.ts
  gen/js/app/mltraining/v1/ml_training_pb.js
  gen/js/app/mltraining/v1/ml_training_pb_service.d.ts
  gen/js/app/mltraining/v1/ml_training_pb_service.js
  proto/viam/app/mltraining/v1/ml_training.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: safe to test, ready-for-protos

#535 [APP-5417]: Accommodate pagination for GetRobotPartHistory in api
  app/v1/app.pb.go
  component/arm/v1/arm.pb.gw.go
  component/encoder/v1/encoder.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/generic/v1/generic.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  proto/viam/app/v1/app.proto
  service/sensors/v1/sensors.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/slam/v1/slam.pb.gw.go
Labels: protos-compiled, safe to test

#536 [APP-5417]: Undo APP-5417
  app/v1/app.pb.go
  component/arm/v1/arm.pb.gw.go
  component/audioinput/v1/audioinput.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/posetracker/v1/pose_tracker.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  component/servo/v1/servo.pb.gw.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  gen/js/google/api/expr/v1alpha1/syntax_pb.d.ts
  gen/js/google/api/expr/v1alpha1/syntax_pb.js
  proto/viam/app/v1/app.proto
  service/datamanager/v1/data_manager.pb.gw.go
  service/navigation/v1/navigation.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled, safe to test

#537 RSDK-8381 add viam server version to API
  component/audioinput/v1/audioinput.pb.gw.go
  component/base/v1/base.pb.gw.go
  component/camera/v1/camera.pb.gw.go
  component/gantry/v1/gantry.pb.gw.go
  component/gripper/v1/gripper.pb.gw.go
  component/inputcontroller/v1/input_controller.pb.gw.go
  component/motor/v1/motor.pb.gw.go
  component/powersensor/v1/powersensor.pb.gw.go
  gen/js/robot/v1/robot_grpc_web_pb.js
  gen/js/robot/v1/robot_pb.d.ts
  gen/js/robot/v1/robot_pb.js
  gen/js/robot/v1/robot_pb_service.d.ts
  gen/js/robot/v1/robot_pb_service.js
  proto/viam/robot/v1/robot.proto
  robot/v1/robot.pb.go
  robot/v1/robot.pb.gw.go
  robot/v1/robot_grpc.pb.go
  service/navigation/v1/navigation.pb.gw.go
  service/sensors/v1/sensors.pb.gw.go
  service/shell/v1/shell.pb.gw.go
  service/vision/v1/vision.pb.gw.go
Labels: protos-compiled, safe to test
