Repository viamrobotics/api, pull requests merged in 2025-01, with the labels that each got.

#612 APP-6581: Support granular billing SKUs in protos
  app/v1/billing.pb.go
  gen/js/app/v1/billing_pb.d.ts
  gen/js/app/v1/billing_pb.js
  proto/viam/app/v1/billing.proto
Labels: protos-compiled, safe to test

#611 [RSDK-9619] Add API for Discover Service and GetModelsFromModules
  gen/js/robot/v1/robot_grpc_web_pb.js
  gen/js/robot/v1/robot_pb.d.ts
  gen/js/robot/v1/robot_pb.js
  gen/js/robot/v1/robot_pb_service.d.ts
  gen/js/robot/v1/robot_pb_service.js
  gen/js/service/discovery/v1/discovery_grpc_web_pb.js
  gen/js/service/discovery/v1/discovery_pb.d.ts
  gen/js/service/discovery/v1/discovery_pb.js
  gen/js/service/discovery/v1/discovery_pb_service.d.ts
  gen/js/service/discovery/v1/discovery_pb_service.js
  proto/viam/robot/v1/robot.proto
  proto/viam/service/discovery/v1/discovery.proto
  robot/v1/robot.pb.go
  robot/v1/robot.pb.gw.go
  robot/v1/robot_grpc.pb.go
  service/discovery/v1/discovery.pb.go
  service/discovery/v1/discovery.pb.gw.go
  service/discovery/v1/discovery_grpc.pb.go
Labels: protos-compiled, safe to test

#618 APP-7475: Make enum consistent for training logs
  app/v1/billing.pb.go
  gen/js/app/v1/billing_pb.d.ts
  gen/js/app/v1/billing_pb.js
  proto/viam/app/v1/billing.proto
Labels: safe to test, ready-for-protos

#621 [RSDK-9632] Add deprecation notice to DiscoverComponents in API Repo
  proto/viam/robot/v1/robot.proto
  robot/v1/robot.pb.go
  robot/v1/robot_grpc.pb.go
Labels: protos-compiled, safe to test

#615 APP-6993: Deprecate legacy auth app apis
  app/v1/end_user.pb.go
  app/v1/end_user_grpc.pb.go
  proto/viam/app/v1/end_user.proto
Labels: safe to test

#622 APP-7502: Update FragmentHistoryEntry for fragment versioning
  app/v1/app.pb.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  proto/viam/app/v1/app.proto
Labels: protos-compiled, safe to test

#619 APP-7497: Add Button and Switch APIs
  component/button/v1/button.pb.go
  component/button/v1/button.pb.gw.go
  component/button/v1/button_grpc.pb.go
  component/switch/v1/switch.pb.go
  component/switch/v1/switch.pb.gw.go
  component/switch/v1/switch_grpc.pb.go
  gen/js/component/button/v1/button_grpc_web_pb.js
  gen/js/component/button/v1/button_pb.d.ts
  gen/js/component/button/v1/button_pb.js
  gen/js/component/button/v1/button_pb_service.d.ts
  gen/js/component/button/v1/button_pb_service.js
  gen/js/component/switch/v1/switch_grpc_web_pb.js
  gen/js/component/switch/v1/switch_pb.d.ts
  gen/js/component/switch/v1/switch_pb.js
  gen/js/component/switch/v1/switch_pb_service.d.ts
  gen/js/component/switch/v1/switch_pb_service.js
  proto/viam/component/button/v1/button.proto
  proto/viam/component/switch/v1/switch.proto
Labels: protos-compiled, safe to test

#623 RSDK-9760 - Tunnelling traffic over grpc
  gen/js/robot/v1/robot_pb.d.ts
  gen/js/robot/v1/robot_pb.js
  gen/js/robot/v1/robot_pb_service.d.ts
  gen/js/robot/v1/robot_pb_service.js
  proto/viam/robot/v1/robot.proto
  robot/v1/robot.pb.go
  robot/v1/robot.pb.gw.go
  robot/v1/robot_grpc.pb.go
Labels: protos-compiled, safe to test

#624 Add country to Billing Address for white-labelled billing
  app/v1/app.pb.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  proto/viam/app/v1/app.proto
Labels: safe to test, ready-for-protos

#625 bump x/crypto 0.24 -> 0.31
  go.mod
  go.sum
Labels: protos-compiled, safe to test

#610 APP-7267 APP-7269 Add version support to GetFragment
  app/v1/app.pb.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  proto/viam/app/v1/app.proto
Labels: protos-compiled, safe to test
