Repository viamrobotics/api, pull requests merged in 2025-08, with the labels that each got.

#729 DATA-4309: Remove UpdateDataPipeline and add RenameDataPipeline
  proto/viam/app/datapipelines/v1/data_pipelines.proto
Labels: ready-for-protos

#731 bump x/oauth2
  go.mod
  go.sum
Labels: protos-compiled, safe to test

#737 Document ListMachineSummaries optional OrganizationID input
  app/v1/app.pb.go
  proto/viam/app/v1/app.proto
Labels: protos-compiled, safe to test

#738 Add ID to proto
  app/data/v1/data.pb.go
  gen/js/app/data/v1/data_pb.d.ts
  gen/js/app/data/v1/data_pb.js
  proto/viam/app/data/v1/data.proto
Labels: protos-compiled, safe to test

#741 DATA-4466: Make MergeDatasets API public
  app/dataset/v1/dataset.pb.go
  app/dataset/v1/dataset.pb.gw.go
  app/dataset/v1/dataset_grpc.pb.go
  gen/js/app/dataset/v1/dataset_grpc_web_pb.js
  gen/js/app/dataset/v1/dataset_pb.d.ts
  gen/js/app/dataset/v1/dataset_pb.js
  gen/js/app/dataset/v1/dataset_pb_service.d.ts
  gen/js/app/dataset/v1/dataset_pb_service.js
  proto/viam/app/dataset/v1/dataset.proto
Labels: protos-compiled, safe to test

#743 RSDK-11542 - Update GetImagesRequest and Image
  component/camera/v1/camera.pb.go
  gen/js/component/camera/v1/camera_pb.d.ts
  gen/js/component/camera/v1/camera_pb.js
  proto/viam/component/camera/v1/camera.proto
Labels: protos-compiled, safe to test

#742 [APP-9093] Define protos for `CreateInvoiceAndChargeImmediately` method
  app/v1/billing.pb.go
  app/v1/billing.pb.gw.go
  app/v1/billing_grpc.pb.go
  gen/js/app/v1/billing_grpc_web_pb.js
  gen/js/app/v1/billing_pb.d.ts
  gen/js/app/v1/billing_pb.js
  gen/js/app/v1/billing_pb_service.d.ts
  gen/js/app/v1/billing_pb_service.js
  proto/viam/app/v1/billing.proto
Labels: protos-compiled, safe to test

#733 DATA-3781: Deprecate AddTagsToBinaryDataByFilter, RemoveTagsFromBinaryDataByFilter
  app/data/v1/data.pb.go
  app/data/v1/data_grpc.pb.go
  proto/viam/app/data/v1/data.proto
Labels: protos-compiled, safe to test

#724 DATA-4315 - UploadBinaryDataToDataset in data manager
  gen/js/service/datamanager/v1/data_manager_grpc_web_pb.js
  gen/js/service/datamanager/v1/data_manager_pb.d.ts
  gen/js/service/datamanager/v1/data_manager_pb.js
  gen/js/service/datamanager/v1/data_manager_pb_service.d.ts
  gen/js/service/datamanager/v1/data_manager_pb_service.js
  proto/viam/service/datamanager/v1/data_manager.proto
  service/datamanager/v1/data_manager.pb.go
  service/datamanager/v1/data_manager.pb.gw.go
  service/datamanager/v1/data_manager_grpc.pb.go
Labels: protos-compiled, safe to test

#748 DATA-3163 - Deprecate TagsByFilter and BoundingBoxesByFilter
  app/data/v1/data.pb.go
  app/data/v1/data_grpc.pb.go
  proto/viam/app/data/v1/data.proto
Labels: protos-compiled, safe to test

#750 add PseudolinearConstraint
  gen/js/service/motion/v1/motion_pb.d.ts
  gen/js/service/motion/v1/motion_pb.js
  proto/viam/service/motion/v1/motion.proto
  service/motion/v1/motion.pb.go
Labels: safe to test
