Repository viamrobotics/api, pull requests merged in 2025-04, with the labels that each got.

#662 APP-7929 add markdown descriptions to module and version history
  app/v1/app.pb.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  proto/viam/app/v1/app.proto
Labels: protos-compiled, safe to test

#663 APP-7929 add markdown description to moduleversion
  app/v1/app.pb.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  proto/viam/app/v1/app.proto
Labels: protos-compiled, safe to test

#665 DATA-3917 Change TabularDataByMQL format
  app/data/v1/data.pb.go
  gen/js/app/data/v1/data_pb.d.ts
  gen/js/app/data/v1/data_pb.js
  proto/viam/app/data/v1/data.proto
Labels: protos-compiled, safe to test, ready-for-protos

#666 Change name of standard storage option
  app/data/v1/data.pb.go
  gen/js/app/data/v1/data_pb.d.ts
  gen/js/app/data/v1/data_pb.js
  proto/viam/app/data/v1/data.proto
Labels: protos-compiled, safe to test, ready-for-protos

#668 APP-7932: Add rename module protos
  app/v1/app.pb.go
  app/v1/app.pb.gw.go
  app/v1/app_grpc.pb.go
  gen/js/app/v1/app_grpc_web_pb.js
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  gen/js/app/v1/app_pb_service.d.ts
  gen/js/app/v1/app_pb_service.js
  proto/viam/app/v1/app.proto
Labels: protos-compiled, safe to test

#664 DATA-3956 Add protos for enable/disable endpoints
  app/datapipelines/v1/data_pipelines.pb.go
  app/datapipelines/v1/data_pipelines.pb.gw.go
  app/datapipelines/v1/data_pipelines_grpc.pb.go
  gen/js/app/datapipelines/v1/data_pipelines_grpc_web_pb.js
  gen/js/app/datapipelines/v1/data_pipelines_pb.d.ts
  gen/js/app/datapipelines/v1/data_pipelines_pb.js
  gen/js/app/datapipelines/v1/data_pipelines_pb_service.d.ts
  gen/js/app/datapipelines/v1/data_pipelines_pb_service.js
  proto/viam/app/datapipelines/v1/data_pipelines.proto
Labels: protos-compiled, safe to test

#671 DATA-3916 Add protos for pipeline tracking
  app/datapipelines/v1/data_pipelines.pb.go
  app/datapipelines/v1/data_pipelines.pb.gw.go
  app/datapipelines/v1/data_pipelines_grpc.pb.go
  gen/js/app/datapipelines/v1/data_pipelines_grpc_web_pb.js
  gen/js/app/datapipelines/v1/data_pipelines_pb.d.ts
  gen/js/app/datapipelines/v1/data_pipelines_pb.js
  gen/js/app/datapipelines/v1/data_pipelines_pb_service.d.ts
  gen/js/app/datapipelines/v1/data_pipelines_pb_service.js
  proto/viam/app/datapipelines/v1/data_pipelines.proto
Labels: protos-compiled, safe to test

#673 DATA-3916 Remove reason
  app/datapipelines/v1/data_pipelines.pb.go
  gen/js/app/datapipelines/v1/data_pipelines_pb.d.ts
  gen/js/app/datapipelines/v1/data_pipelines_pb.js
  proto/viam/app/datapipelines/v1/data_pipelines.proto
Labels: protos-compiled, safe to test

#658 DATA-3866 Deprecate binary ids struct in proto.
  app/data/v1/data.pb.go
  app/datasync/v1/data_sync.pb.go
  proto/viam/app/data/v1/data.proto
  proto/viam/app/datasync/v1/data_sync.proto
Labels: protos-compiled, safe to test

#674 DATA-3866 Fix deprecation markings
  app/data/v1/data.pb.go
  app/datasync/v1/data_sync.pb.go
  proto/viam/app/data/v1/data.proto
  proto/viam/app/datasync/v1/data_sync.proto
Labels: protos-compiled, safe to test

#670 APP-8055 add optional field to verify last known update for updating robot parts and fragments
  app/v1/app.pb.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  gen/js/google/rpc/error_details_pb.d.ts
  gen/js/google/rpc/error_details_pb.js
  proto/viam/app/v1/app.proto
Labels: safe to test, ready-for-protos

#680 Add no TLS to network config proto
  app/v1/robot.pb.go
  gen/js/app/v1/robot_pb.d.ts
  gen/js/app/v1/robot_pb.js
  proto/viam/app/v1/robot.proto
Labels: protos-compiled, safe to test

#683 APP-7933: Add `UpdateOrganizationNamespace` protos
  app/v1/app.pb.go
  app/v1/app.pb.gw.go
  app/v1/app_grpc.pb.go
  gen/js/app/v1/app_grpc_web_pb.js
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  gen/js/app/v1/app_pb_service.d.ts
  gen/js/app/v1/app_pb_service.js
  proto/viam/app/v1/app.proto
Labels: protos-compiled, safe to test

#684 APP-7933: Make `new_public_namespace` required in `UpdateOrganizationNamespaceRequest`
  app/v1/app.pb.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  proto/viam/app/v1/app.proto
Labels: protos-compiled, safe to test

#688 bump x/net
  go.mod
  go.sum
Labels: protos-compiled, safe to test
