Repository viamrobotics/api, pull requests merged in 2025-06, with the labels that each got.

#702 APP-8364: Add GetRobotPartByNameAndLocation API
  app/v1/app.pb.go
  app/v1/app.pb.gw.go
  app/v1/app_grpc.pb.go
  gen/js/app/v1/app_grpc_web_pb.js
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  gen/js/app/v1/app_pb_service.d.ts
  gen/js/app/v1/app_pb_service.js
  proto/viam/app/v1/app.proto
Labels: safe to test, ready-for-protos

#694 DATA-4145: add enable_backfill to CreateDataPipeline
  app/datapipelines/v1/data_pipelines.pb.go
  gen/js/app/datapipelines/v1/data_pipelines_pb.d.ts
  gen/js/app/datapipelines/v1/data_pipelines_pb.js
  proto/viam/app/datapipelines/v1/data_pipelines.proto
Labels: protos-compiled, safe to test

#703 [APP-8317] Add FragmentID Filter to ListMachineSummaries
  app/v1/app.pb.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  proto/viam/app/v1/app.proto
Labels: protos-compiled, safe to test

#704 [APP-8431] Add ExitProvisioning(), agent_version field
  gen/js/provisioning/v1/provisioning_grpc_web_pb.js
  gen/js/provisioning/v1/provisioning_pb.d.ts
  gen/js/provisioning/v1/provisioning_pb.js
  gen/js/provisioning/v1/provisioning_pb_service.d.ts
  gen/js/provisioning/v1/provisioning_pb_service.js
  proto/viam/provisioning/v1/provisioning.proto
  provisioning/v1/provisioning.pb.go
  provisioning/v1/provisioning.pb.gw.go
  provisioning/v1/provisioning_grpc.pb.go
Labels: safe to test, ready-for-protos

#705 DATA-4225: API change for recent data
  app/datapipelines/v1/data_pipelines.pb.go
  gen/js/app/datapipelines/v1/data_pipelines_grpc_web_pb.js
  gen/js/app/datapipelines/v1/data_pipelines_pb.d.ts
  gen/js/app/datapipelines/v1/data_pipelines_pb.js
  proto/viam/app/datapipelines/v1/data_pipelines.proto
Labels: protos-compiled, safe to test, ready-for-protos

#701 APP-8285: Pass current OrganizationID into namespace check
  app/v1/app.pb.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  proto/viam/app/v1/app.proto
Labels: safe to test, ready-for-protos

#709 APP-8270: Update "last login" to "last access"
  app/v1/app.pb.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  proto/viam/app/v1/app.proto
Labels: protos-compiled, safe to test

#714 DATA-4276: API Change for ExportTabularData and GetLatestData to accept optional additional_params
  app/data/v1/data.pb.go
  gen/js/app/data/v1/data_pb.d.ts
  gen/js/app/data/v1/data_pb.js
  proto/viam/app/data/v1/data.proto
Labels: protos-compiled, safe to test
