Repository viamrobotics/api, pull requests merged in 2025-02, with the labels that each got.

#616 APP-7407 Add getFragmentUsage endpoint
  app/v1/app.pb.go
  app/v1/app.pb.gw.go
  app/v1/app_grpc.pb.go
  gen/js/app/v1/app_grpc_web_pb.js
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  gen/js/app/v1/app_pb_service.d.ts
  gen/js/app/v1/app_pb_service.js
  proto/viam/app/v1/app.proto
Labels: protos-compiled, safe to test

#627 APP-7445: Add fragment tag-related requests
  app/v1/app.pb.go
  app/v1/app.pb.gw.go
  app/v1/app_grpc.pb.go
  gen/js/app/v1/app_grpc_web_pb.js
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  gen/js/app/v1/app_pb_service.d.ts
  gen/js/app/v1/app_pb_service.js
  gen/js/google/api/client_pb.d.ts
  gen/js/google/api/client_pb.js
  proto/viam/app/v1/app.proto
Labels: protos-compiled, safe to test

#620 DATA-3662 Add recent data SKUs to proto
  app/v1/billing.pb.go
  gen/js/app/v1/billing_pb.d.ts
  gen/js/app/v1/billing_pb.js
  gen/js/google/api/client_pb.d.ts
  gen/js/google/api/client_pb.js
  proto/viam/app/v1/billing.proto
Labels: protos-compiled, safe to test

#630 [APP-3239] Define protos for user-defined metadata
  app/v1/app.pb.go
  app/v1/app.pb.gw.go
  app/v1/app_grpc.pb.go
  gen/js/app/v1/app_grpc_web_pb.js
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  gen/js/app/v1/app_pb_service.d.ts
  gen/js/app/v1/app_pb_service.js
  proto/viam/app/v1/app.proto
Labels: safe to test

#628 [APP-7210] Update Agent Proto
  app/agent/v1/agent.pb.go
  gen/js/app/agent/v1/agent_pb.d.ts
  gen/js/app/agent/v1/agent_pb.js
  proto/viam/app/agent/v1/agent.proto
Labels: protos-compiled, safe to test, ready-for-protos

#629 APP-7615 Update list machine fragments to support versions
  app/v1/app.pb.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  proto/viam/app/v1/app.proto
Labels: protos-compiled, safe to test

#634 RSDK-9861 Add tunnel ports and connection timeouts to network config
  app/v1/robot.pb.go
  gen/js/app/v1/robot_pb.d.ts
  gen/js/app/v1/robot_pb.js
  proto/viam/app/v1/robot.proto
Labels: safe to test
