Repository viamrobotics/api, pull requests merged in 2025-03, with the labels that each got.

#636 RSDK-9862 Add ListTunnels to robot API
  gen/js/robot/v1/robot_grpc_web_pb.js
  gen/js/robot/v1/robot_pb.d.ts
  gen/js/robot/v1/robot_pb.js
  gen/js/robot/v1/robot_pb_service.d.ts
  gen/js/robot/v1/robot_pb_service.js
  proto/viam/robot/v1/robot.proto
  robot/v1/robot.pb.go
  robot/v1/robot.pb.gw.go
  robot/v1/robot_grpc.pb.go
Labels: protos-compiled, safe to test

#633 APP-7667: Adding org name to the Locations struct
  app/v1/app.pb.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  proto/viam/app/v1/app.proto
Labels: protos-compiled, safe to test

#637 DATA-3852 Add new field for binary data id
  app/data/v1/data.pb.go
  app/datasync/v1/data_sync.pb.go
  app/mlinference/v1/ml_inference.pb.go
  gen/js/app/data/v1/data_pb.d.ts
  gen/js/app/data/v1/data_pb.js
  gen/js/app/datasync/v1/data_sync_pb.d.ts
  gen/js/app/datasync/v1/data_sync_pb.js
  gen/js/app/mlinference/v1/ml_inference_pb.d.ts
  gen/js/app/mlinference/v1/ml_inference_pb.js
  proto/viam/app/data/v1/data.proto
  proto/viam/app/datasync/v1/data_sync.proto
  proto/viam/app/mlinference/v1/ml_inference.proto
Labels: protos-compiled, safe to test

#639 [APP-7779] Update protos to return metadata as a single struct
  app/v1/app.pb.go
  gen/js/app/v1/app_grpc_web_pb.js
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  proto/viam/app/v1/app.proto
Labels: safe to test, ready-for-protos

#640 [RSDK-10140] add relative bounding box coordinates to detections
  gen/js/service/vision/v1/vision_pb.d.ts
  gen/js/service/vision/v1/vision_pb.js
  proto/viam/service/vision/v1/vision.proto
  service/vision/v1/vision.pb.go
Labels: protos-compiled, safe to test

#643 [APP-7778] Implement GetAppContent API
  app/v1/app.pb.go
  app/v1/app.pb.gw.go
  app/v1/app_grpc.pb.go
  gen/js/app/v1/app_grpc_web_pb.js
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  gen/js/app/v1/app_pb_service.d.ts
  gen/js/app/v1/app_pb_service.js
  proto/viam/app/v1/app.proto
Labels: protos-compiled, safe to test

#641 [APP-7781] Update UploadModule API to include viam apps functionality
  app/v1/app.pb.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  proto/viam/app/v1/app.proto
Labels: protos-compiled, safe to test

#645 Add ListMachineSummaries API
  app/v1/app.pb.go
  app/v1/app.pb.gw.go
  app/v1/app_grpc.pb.go
  gen/js/app/v1/app_grpc_web_pb.js
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  gen/js/app/v1/app_pb_service.d.ts
  gen/js/app/v1/app_pb_service.js
  proto/viam/app/v1/app.proto
Labels: safe to test, ready-for-protos

#647 DATA-3768 - Add ModelFramework to SubmitTrainingJobRequest
  app/mltraining/v1/ml_training.pb.go
  gen/js/app/mltraining/v1/ml_training_pb.d.ts
  gen/js/app/mltraining/v1/ml_training_pb.js
  proto/viam/app/mltraining/v1/ml_training.proto
Labels: safe to test, ready-for-protos

#649 use git-access-token
  .github/workflows/tag_and_release_protos.yml
Labels: safe to test

#650 Revert "use git-access-token"
  .github/workflows/tag_and_release_protos.yml
Labels: safe to test

#648 RSDK-10250 add mesh type to geometry oneof
  common/v1/common.pb.go
  gen/js/common/v1/common_pb.d.ts
  gen/js/common/v1/common_pb.js
  proto/viam/common/v1/common.proto
Labels: protos-compiled, safe to test

#638 [RSDK-9633] delete discover components
  proto/viam/robot/v1/robot.proto
Labels: safe to test

#651 DATA-3911 Add CRUD protos for data pipelines
  app/data/v1/data.pb.go
  app/data/v1/data.pb.gw.go
  app/data/v1/data_grpc.pb.go
  gen/js/app/data/v1/data_grpc_web_pb.js
  gen/js/app/data/v1/data_pb.d.ts
  gen/js/app/data/v1/data_pb.js
  gen/js/app/data/v1/data_pb_service.d.ts
  gen/js/app/data/v1/data_pb_service.js
  gen/js/robot/v1/robot_grpc_web_pb.js
  gen/js/robot/v1/robot_pb.d.ts
  gen/js/robot/v1/robot_pb.js
  gen/js/robot/v1/robot_pb_service.d.ts
  gen/js/robot/v1/robot_pb_service.js
  proto/viam/app/data/v1/data.proto
  robot/v1/robot.pb.go
  robot/v1/robot.pb.gw.go
  robot/v1/robot_grpc.pb.go
Labels: protos-compiled, safe to test

#653 DATA-3911 Move data pipeline protos
  app/data/v1/data.pb.go
  app/data/v1/data.pb.gw.go
  app/data/v1/data_grpc.pb.go
  app/datapipelines/v1/data_pipelines.pb.go
  app/datapipelines/v1/data_pipelines.pb.gw.go
  app/datapipelines/v1/data_pipelines_grpc.pb.go
  gen/js/app/data/v1/data_grpc_web_pb.js
  gen/js/app/data/v1/data_pb.d.ts
  gen/js/app/data/v1/data_pb.js
  gen/js/app/data/v1/data_pb_service.d.ts
  gen/js/app/data/v1/data_pb_service.js
  gen/js/app/datapipelines/v1/data_pipelines_grpc_web_pb.js
  gen/js/app/datapipelines/v1/data_pipelines_pb.d.ts
  gen/js/app/datapipelines/v1/data_pipelines_pb.js
  gen/js/app/datapipelines/v1/data_pipelines_pb_service.d.ts
  gen/js/app/datapipelines/v1/data_pipelines_pb_service.js
  proto/viam/app/data/v1/data.proto
  proto/viam/app/datapipelines/v1/data_pipelines.proto
Labels: protos-compiled, safe to test

#655 [APP-7778] Define `GetAppContent` API
  app/v1/app.pb.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  proto/viam/app/v1/app.proto
Labels: protos-compiled, safe to test

#654 DATA-3911 Refine request/response protos
  app/datapipelines/v1/data_pipelines.pb.go
  gen/js/app/datapipelines/v1/data_pipelines_pb.d.ts
  gen/js/app/datapipelines/v1/data_pipelines_pb.js
  proto/viam/app/datapipelines/v1/data_pipelines.proto
Labels: protos-compiled, safe to test

#657 DATA-3917 Add 'use_data_pipeline' option
  app/data/v1/data.pb.go
  gen/js/app/data/v1/data_pb.d.ts
  gen/js/app/data/v1/data_pb.js
  proto/viam/app/data/v1/data.proto
Labels: protos-compiled, safe to test

#656 APP-7137: support getting and setting billing tiers
  app/v1/app.pb.go
  app/v1/billing.pb.go
  app/v1/billing.pb.gw.go
  app/v1/billing_grpc.pb.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  gen/js/app/v1/billing_grpc_web_pb.js
  gen/js/app/v1/billing_pb.d.ts
  gen/js/app/v1/billing_pb.js
  gen/js/app/v1/billing_pb_service.d.ts
  gen/js/app/v1/billing_pb_service.js
  proto/viam/app/v1/app.proto
  proto/viam/app/v1/billing.proto
Labels: protos-compiled, safe to test

#660 APP-7929 add markdown description to update requests
  app/v1/app.pb.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  proto/viam/app/v1/app.proto
Labels: protos-compiled, safe to test
