Repository viamrobotics/api, pull requests merged in 2025-05, with the labels that each got.

#685 RSDK-10559 Add `optional_dependencies` field to `ValidateConfigResponse`
  gen/js/module/v1/module_pb.d.ts
  gen/js/module/v1/module_pb.js
  module/v1/module.pb.go
  module/v1/module_grpc.pb.go
  proto/viam/module/v1/module.proto
Labels: safe to test

#690 APP-8187: Add apps to Module API
  app/v1/app.pb.go
  gen/js/app/v1/app_pb.d.ts
  gen/js/app/v1/app_pb.js
  proto/viam/app/v1/app.proto
Labels: bug, protos-compiled, safe to test, ready-for-protos

#687 Replace bare link with markdown-style link to appease downstream Hugo/Vale linting
  proto/viam/robot/v1/robot.proto
  proto/viam/service/slam/v1/slam.proto
Labels: safe to test

#693 DATA-3969 - Add custom args to training metadata
  app/mltraining/v1/ml_training.pb.go
  gen/js/app/mltraining/v1/ml_training_pb.d.ts
  gen/js/app/mltraining/v1/ml_training_pb.js
  proto/viam/app/mltraining/v1/ml_training.proto
  robot/v1/robot.pb.go
  service/slam/v1/slam.pb.go
Labels: protos-compiled, safe to test

#689 RSDK-10574 - Add Kinematics API method to Gripper
  component/gripper/v1/gripper.pb.go
  component/gripper/v1/gripper.pb.gw.go
  component/gripper/v1/gripper_grpc.pb.go
  gen/js/component/gripper/v1/gripper_grpc_web_pb.js
  gen/js/component/gripper/v1/gripper_pb_service.d.ts
  gen/js/component/gripper/v1/gripper_pb_service.js
  proto/viam/component/gripper/v1/gripper.proto
Labels: safe to test, ready-for-protos
